[project]
name = "wiki_pdf"
authors = [
    { name = "Mercy Selvanayagi", email = "mercy.selvanayagi@azimpremjifoundation.org"}
]
description = "Custom App for Wiki PDF Download"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "weasyprint>=62.0",
    "markdown2>=2.4",
    "beautifulsoup4>=4.12",
    "pypdf>=4.0",
    "google-cloud-translate>=3.15",
    "google-generativeai>=0.8",
    "anthropic>=0.34",
    "groq>=1.5.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0 <16.0.0"
